# Default values for localstorage-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

channel_lso_operator: stable
version_lso_opertor: local-storage-operator.4.11.0-202304181642

lso_planApproval: Automatic
lso_nodes:
  - ip-10-0-133-81.eu-central-1.compute.internal
  - ip-10-0-138-165.eu-central-1.compute.internal
  - ip-10-0-180-173.eu-central-1.compute.internal
  - ip-10-0-186-172.eu-central-1.compute.internal

lso_storageClassName: lso-volumeset
