apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeDiscovery
metadata:
  name: auto-discover-devices
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - ip-10-0-136-213.eu-central-1.compute.internal
        - ip-10-0-153-182.eu-central-1.compute.internal
        - ip-10-0-167-178.eu-central-1.compute.internal
        - ip-10-0-181-68.eu-central-1.compute.internal
