apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  monDataDirHostPath: /var/lib/rook
  version: {{ .Values.version_storagecluster }}
  storageDeviceSets:
    - count: {{ .Values.count_storageDeviceSets }}
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '1'
          storageClassName: {{ .Values.lso_storageClassName }}
          volumeMode: Block
      name: ocs-deviceset-{{ .Values.lso_storageClassName }}
      replica: {{ .Values.replicaCount }}
