# Default values for odf-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

version_storagecluster: 4.11.0
count_storageDeviceSets: 4
lso_storageClassName: lso-volumeset

channel_odf_operator: stable-4.11
version_odf_opertor: odf-operator.v4.11.8

odf_planApproval: Automatic
